

name: Java Maven Build & Publish Artifact

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

   
  publish-job:
    runs-on: ubuntu-latest
    needs: build_test
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - run: mvn --batch-mode --update-snapshots verify
    - run: mkdir staging && cp target/*.jar staging
    - uses: actions/upload-artifact@v3
      with:
        name: Package
        path: staging

    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build Docker image
      run: docker build -t ksiva27/sample-maven-java:1.0 .

    - name: Push Docker image to Docker Hub
      run: docker push ksiva27/sample-maven-java:1.0

   # - name: Build & push Docker image
   #   uses: mr-smithers-excellent/docker-build-push@v5
   #   with:
    #    image: cmakkaya/my-github-action-app
    #    tags: latest
     #   registry: docker.io
     #   dockerfile: Dockerfile
     #   username: ${{ secrets.DOCKERHUB_USERNAME }}
     #   password: ${{ secrets.DOCKERHUB_PASSWORD }}
 

