name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Copy Jar file
      run: mv build/libs/$(ls build/libs) app.jar

    - uses: actions/upload-artifact@master
      with:
          name: jar-file
          path: app.jar
    - name: Build Docker image
      run: docker build -t ksiva27/smj:1.0 -f Dockerfile .
      
    - name: Push Docker image to Docker Hub
      run: docker push ksiva27/smj:1.0
