name: Java Maven Build, Dockerize, and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
   
  dockerize:
    runs-on: ubuntu-latest
    needs: build_test
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build Docker image
      run: docker build -t my-java-app .
    
    - name: Push Docker image to Docker Hub
      run: docker push my-java-app

  deploy:
    runs-on: ubuntu-latest
    needs: dockerize
    steps:
    - name: Deploy to AWS ECS or EKS
      run: |
        # Use the AWS CLI or eksctl to deploy your application to ECS or EKS
        # Example:
        # aws ecs update-service --cluster my-cluster --service my-service --force-new-deployment
        # or
        # eksctl update cluster --name my-eks-cluster --approve
