name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build Docker image
      run: docker build -t ksiva27/gs-maven:0.1.0 -f Dockerfile .
    
    - name: Push Docker image to Docker Hub
      run: docker push ksiva27/smj:0.1.0

          #docker build -t gs-maven:0.1.0 .

         #docker tag gs-maven:0.1.0 ksiva27/smj:0.1.0

          #docker push ksiva27/smj:0.1.0
