name: Java Maven Build and Docker Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Build with Maven
      run: mvn clean install

    - name: Test
      run: mvn test

    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and Push Docker Image
      run: |
        docker build -t ksiva27/myapp:latest .
        docker push ksiva27/myapp:latest

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1  # Update this to your desired AWS region

    - name: Deploy to Amazon ECS
      run: aws ecs update-service --service my-ecs-service --cluster my-ecs-cluster --force-new-deployment

    - name: Install kubectl
      run: |
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        chmod +x kubectl
        sudo mv kubectl /usr/local/bin/

    - name: Update kubeconfig
      run: aws eks --region us-east-1 update-kubeconfig --name my-eks-cluster

    - name: Deploy to Amazon EKS
      run: kubectl apply -f your-kubernetes-manifest.yml  # Replace with the path to your Kubernetes manifest file
