name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build Docker image
      run: docker build -t your-dockerhub-username/your-image-name:latest .
      working-directory: https://github.com/Siva-creator-ops/sample-maven-java.git
      #./path/to/your/Dockerfile
      
    - name: Build Docker image
      run: docker build -t ksiva27/gs-maven:0.1.0 -f Dockerfile .
    
    - name: Push Docker image to Docker Hub
      run: docker push ksiva27/smj:0.1.0

      #C:\Users\SIVA RAMA KRISHNA\SampleJava\sample-maven-java\Package
